%% DESIGN PROBES FOR UNMASKED REGIONS
% First region
ApOPs(...
    'MS', "C:\Users\manfernandez\Dropbox (CRG ADV)\Manuel Fernandez's files\3.DeLIM Project\B.Projects_scripts\2023-11-16-probe_design\Region1\unmasked\region_1_oligolego.txt",  ...
    'BS', "C:\Users\manfernandez\Dropbox (CRG ADV)\Manuel Fernandez's files\3.DeLIM Project\B.Projects_scripts\2023-11-16-probe_design\Region1\unmasked\region_1_oligolego.txt", ...
    'Streets', "C:\Users\manfernandez\Dropbox (CRG ADV)\Manuel Fernandez's files\3.DeLIM Project\B.Projects_scripts\2023-11-16-probe_design\OligoLego-master\Streets\Streets_hg38.txt", ...
    'PTable', "C:\Users\manfernandez\Dropbox (CRG ADV)\Manuel Fernandez's files\3.DeLIM Project\B.Projects_scripts\2023-11-16-probe_design\OligoLego-master\Streets\PenaltyTable_hg38.txt", ...
    'SavePath', "C:\Users\manfernandez\Dropbox (CRG ADV)\Manuel Fernandez's files\3.DeLIM Project\B.Projects_scripts\2023-11-16-probe_design\Region1\unmasked\", ...
    'MaxAvoid', "22", ...
    'SameUniversal', "C:\Users\manfernandez\Dropbox (CRG ADV)\Manuel Fernandez's files\3.DeLIM Project\B.Projects_scripts\2023-11-16-probe_design\Universal_unmasked.txt" ...
    );